// packages/vue/lib/components/Button/Button.vue
<script setup>
// import type { ButtonProps } from './Button.types.js'

// import './button.css'

// export default function Button({ type, text, onClickHandler }: ButtonProps): React.JSX.Element {
//   return (
    
//   )
// }

</script>

<template>
  <button type="button" :class="`button button-${type}`" @click={onClickHandler}>
    {{ text }}
  </button>
</template>

<style src="./button.css" scoped></style>

// packages/react/lib/button/Button.tsx
import { FC } from 'react'

import type { ButtonProps } from './Button.types.js' // intellisense changed to .js as oppose to .ts
import './button.css'

const Button: FC<ButtonProps> = ({ type, text, onClickHandler }) => {
  return (
    <button type="button" className={`button button-${type}`} onClick={onClickHandler}>
      {text}
    </button>
  )
}

export default Button
