// packages/react/lib/components/Button/Button.tsx
import type { ButtonProps } from './Button.types.js'

import './button.css'

export default function Button({ type, text, onClickHandler }: ButtonProps): React.JSX.Element {
  return (
    <button type="button" className={`button button-${type}`} onClick={onClickHandler}>
      {text}
    </button>
  )
}

// packages/vue/lib/components/Button/Button.vue
<script setup>
// import type { ButtonProps } from './Button.types.js'

// import './button.css'

// export default function Button({ type, text, onClickHandler }: ButtonProps): React.JSX.Element {
//   return (
    
//   )
// }

</script>

<template>
  <button type="button" :class="`button button-${type}`" @click={onClickHandler}>
    {{ text }}
  </button>
</template>

<style src="./button.css" scoped></style>
